version: "3"

services:
  portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    links: [root, colab, lotsizing, monitor]
    environment:
      DOMAINS: "industrial360utec.com -> http://root:8080, colaboratorio.industrial360utec.com -> http://colab:8080, lotsizing.industrial360utec.com -> http://lotsizing:8080, monitor.industrial360utec.com -> http://monitor:3000"
      STAGE: "production"

  monitor:
    image: grafana/grafana
    links: [prometheus]

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
      - "./data:/prometheus"
    links: [root, colab, lotsizing]

  root:
    image: bregymr/redirect
    environment:
      REDIRECT_URL: https://www.notion.so/colaboratorioutec/INGENIER-A-INDUSTRIAL-2d551d72763f4447bad3356b1f86188e
  colab:
    image: bregymr/redirect
    environment:
      REDIRECT_URL: https://www.notion.so/COLABORATORIO-UTEC-da1558601b864c46b8596d1346f2605a
  lotsizing:
    image: bregymr/redirect
    environment:
      REDIRECT_URL: https://www.notion.so/colaboratorioutec/Lotsizing-8a55c61618a94ed795856589b67404d4
