version: "3"

services:
  root:
    image: "bregymr/redirect"
    environment:
      - REDIRECT_URL=https://www.notion.so/colaboratorioutec/INGENIER-A-INDUSTRIAL-2d551d72763f4447bad3356b1f86188e
      - REDIRECT_CODE=302
      - ROUTE=/
      - PORT=8080
